dataset:
  ids:
    - "vidore/arxivqa_test_subsampled"
    - "vidore/docvqa_test_subsampled"
    - "vidore/infovqa_test_subsampled"
    - "vidore/tabfquad_test_subsampled"
    - "vidore/tatdqa_test"
    - "vidore/shiftproject_test"
    - "vidore/syntheticDocQA_artificial_intelligence_test"
    - "vidore/syntheticDocQA_energy_test"
    - "vidore/syntheticDocQA_government_reports_test"
    - "vidore/syntheticDocQA_healthcare_industry_test"
  preferred_splits:
    - "test"
    - "validation"
    - "train"

processing:
  max_rows_per_split: null
  save_images: true
  image_format: "png"
